name: neuralbody
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - pytorch=2.0.0
  - torchvision
  - pip
  - open3d
  - PyYAML=5.3.1
  - tqdm=4.28.1
  - tensorboardX=1.2
  - termcolor=1.1.0
  - imageio=2.3.0
  - pip:
    - opencv-contrib-python>=3.4.2.17
    - opencv-python>=3.4.2.17,<4
    - trimesh==3.8.15
    - plyfile==0.6
    - PyMCubes==0.1.0
    - pyglet==1.4.0b1
    - chumpy